### ISSUE TITLE
Integrate some of the lessons/wording from other CoCs

### ISSUE THREAD

**Issue by kern** [HackathonHackers/code-of-conduct#6]
For example, I really appreciate how concise the one from [EA Global](http://www.eaglobal.org/codeofconduct/) is.

**Comment by rubinovitz** [comment]
@kern I don't think it has enough coverage.

**Comment by rubinovitz** [comment]
It just says don't harass people, basically.

**Comment by rubinovitz** [comment]
I'd rather have something lean + appendix so I don't have to keep typing people things over and over.
Also that leaner CoC ignores HH nuances such as hiring, buy/sell, posting private information, and the reversals.

**Comment by hellyeah** [comment]
What other Code of Conducts have we seen that we like?

**Comment by hellyeah** [comment]
@evaz mentioned Snapchat's Code of Conduct was recommended at one point, I think.

**Comment by kern** [comment]
I think ours is pretty good now. :)
