### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zachlatta** [HackathonHackers/code-of-conduct#8]
The code-of-conduct isn't provided under any sort of license, which makes it difficult for other organizations and initiatives to use.

May I suggest putting it in the public domain or under one of the [Creative Commons](http://creativecommons.org/) licenses?

**Comment by zachlatta** [comment]
Also, just for context, we'd be considering adapting parts of the code-of-conduct over at hackedu/meta#117 if the license permitted it.

**Comment by rubinovitz** [comment]
This is already licensed
https://github.com/HackathonHackers/code-of-conduct/blob/master/README.md#license--attribution

**Comment by zachlatta** [comment]
Ah, my bad! Any chance we could get a file called `LICENSE` or `LICENSE.md` added? Might make it a bit more clear to the less intelligent, like myself.

**Comment by rubinovitz** [comment]
@zachlatta it's cool, that was good feedback. i couldn't even find it for a while. I'll go add the file.

**Comment by hellyeah** [comment]
Merged the PR.
